package com.woniu.mapper;

import com.woniu.entity.BrandTypeExample;
import com.woniu.entity.BrandTypeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrandTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_type
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int countByExample(BrandTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_type
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int deleteByExample(BrandTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_type
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int deleteByPrimaryKey(BrandTypeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_type
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int insert(BrandTypeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_type
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int insertSelective(BrandTypeKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_type
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    List<BrandTypeKey> selectByExample(BrandTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_type
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") BrandTypeKey record, @Param("example") BrandTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand_type
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int updateByExample(@Param("record") BrandTypeKey record, @Param("example") BrandTypeExample example);
}