package com.woniu.mapper;

import com.woniu.entity.Roletree;
import com.woniu.entity.RoletreeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoletreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int countByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int deleteByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int insert(Roletree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int insertSelective(Roletree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    List<Roletree> selectByExample(RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") Roletree record, @Param("example") RoletreeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roletree
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int updateByExample(@Param("record") Roletree record, @Param("example") RoletreeExample example);
}