package com.woniu.mapper;

import com.woniu.entity.ST;
import com.woniu.entity.STExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface STMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int countByExample(STExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int deleteByExample(STExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int insert(ST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int insertSelective(ST record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    List<ST> selectByExample(STExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") ST record, @Param("example") STExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_t
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    int updateByExample(@Param("record") ST record, @Param("example") STExample example);
}