package com.woniu.entity;

public class Adminrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminrole.aid
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column adminrole.rid
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminrole.aid
     *
     * @return the value of adminrole.aid
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminrole.aid
     *
     * @param aid the value for adminrole.aid
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column adminrole.rid
     *
     * @return the value of adminrole.rid
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column adminrole.rid
     *
     * @param rid the value for adminrole.rid
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}