package com.woniu.entity;

import java.util.List;

public class Admin {
	
	private List trees;
	
	public List getTrees() {
		return trees;
	}

	public void setTrees(List trees) {
		this.trees = trees;
	}

	private List roles;
	
	
    public List getRoles() {
		return roles;
	}

	public void setRoles(List roles) {
		this.roles = roles;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aid
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    private Integer aid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.aname
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    private String aname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.apass
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    private String apass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.isdelete
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    private Boolean isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aid
     *
     * @return the value of admin.aid
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public Integer getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aid
     *
     * @param aid the value for admin.aid
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public void setAid(Integer aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.aname
     *
     * @return the value of admin.aname
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public String getAname() {
        return aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.aname
     *
     * @param aname the value for admin.aname
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public void setAname(String aname) {
        this.aname = aname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.apass
     *
     * @return the value of admin.apass
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public String getApass() {
        return apass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.apass
     *
     * @param apass the value for admin.apass
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public void setApass(String apass) {
        this.apass = apass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.isdelete
     *
     * @return the value of admin.isdelete
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.isdelete
     *
     * @param isdelete the value for admin.isdelete
     *
     * @mbggenerated Wed Aug 28 20:52:51 CST 2019
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }
}