package com.woniu.entity;

public class BrandTypeKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_type.bid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand_type.tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_type.bid
     *
     * @return the value of brand_type.bid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_type.bid
     *
     * @param bid the value for brand_type.bid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand_type.tid
     *
     * @return the value of brand_type.tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand_type.tid
     *
     * @param tid the value for brand_type.tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}