package com.woniu.entity;

public class Brand {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.bid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.bname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String bname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.state
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.note
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.bid
     *
     * @return the value of brand.bid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.bid
     *
     * @param bid the value for brand.bid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.bname
     *
     * @return the value of brand.bname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.bname
     *
     * @param bname the value for brand.bname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setBname(String bname) {
        this.bname = bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.state
     *
     * @return the value of brand.state
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.state
     *
     * @param state the value for brand.state
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.note
     *
     * @return the value of brand.note
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.note
     *
     * @param note the value for brand.note
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setNote(String note) {
        this.note = note;
    }
}