package com.woniu.entity;

public class Mycollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.cid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.uid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.collectionType
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer collectiontype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.collectionId
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer collectionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.collectionName
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String collectionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.collectionURL
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String collectionurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mycollection.isdelete
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.cid
     *
     * @return the value of mycollection.cid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.cid
     *
     * @param cid the value for mycollection.cid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.uid
     *
     * @return the value of mycollection.uid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.uid
     *
     * @param uid the value for mycollection.uid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.collectionType
     *
     * @return the value of mycollection.collectionType
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getCollectiontype() {
        return collectiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.collectionType
     *
     * @param collectiontype the value for mycollection.collectionType
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setCollectiontype(Integer collectiontype) {
        this.collectiontype = collectiontype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.collectionId
     *
     * @return the value of mycollection.collectionId
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getCollectionid() {
        return collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.collectionId
     *
     * @param collectionid the value for mycollection.collectionId
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setCollectionid(Integer collectionid) {
        this.collectionid = collectionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.collectionName
     *
     * @return the value of mycollection.collectionName
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getCollectionname() {
        return collectionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.collectionName
     *
     * @param collectionname the value for mycollection.collectionName
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setCollectionname(String collectionname) {
        this.collectionname = collectionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.collectionURL
     *
     * @return the value of mycollection.collectionURL
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getCollectionurl() {
        return collectionurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.collectionURL
     *
     * @param collectionurl the value for mycollection.collectionURL
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setCollectionurl(String collectionurl) {
        this.collectionurl = collectionurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mycollection.isdelete
     *
     * @return the value of mycollection.isdelete
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mycollection.isdelete
     *
     * @param isdelete the value for mycollection.isdelete
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}