package com.woniu.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Orderreturn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.orderReturnID
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer orderreturnid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.orderReturnNum
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String orderreturnnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.sid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.uid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.user_oid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer userOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.store_oid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer storeOid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.order_num
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.pid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.price
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.orderReturnTime
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Date orderreturntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.orderReturnStatus
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer orderreturnstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.isdelete
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderreturn.orderReturnNote
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String orderreturnnote;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.orderReturnID
     *
     * @return the value of orderreturn.orderReturnID
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getOrderreturnid() {
        return orderreturnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.orderReturnID
     *
     * @param orderreturnid the value for orderreturn.orderReturnID
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setOrderreturnid(Integer orderreturnid) {
        this.orderreturnid = orderreturnid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.orderReturnNum
     *
     * @return the value of orderreturn.orderReturnNum
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getOrderreturnnum() {
        return orderreturnnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.orderReturnNum
     *
     * @param orderreturnnum the value for orderreturn.orderReturnNum
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setOrderreturnnum(String orderreturnnum) {
        this.orderreturnnum = orderreturnnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.sid
     *
     * @return the value of orderreturn.sid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.sid
     *
     * @param sid the value for orderreturn.sid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.uid
     *
     * @return the value of orderreturn.uid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.uid
     *
     * @param uid the value for orderreturn.uid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.user_oid
     *
     * @return the value of orderreturn.user_oid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getUserOid() {
        return userOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.user_oid
     *
     * @param userOid the value for orderreturn.user_oid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setUserOid(Integer userOid) {
        this.userOid = userOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.store_oid
     *
     * @return the value of orderreturn.store_oid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getStoreOid() {
        return storeOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.store_oid
     *
     * @param storeOid the value for orderreturn.store_oid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setStoreOid(Integer storeOid) {
        this.storeOid = storeOid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.order_num
     *
     * @return the value of orderreturn.order_num
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.order_num
     *
     * @param orderNum the value for orderreturn.order_num
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.pid
     *
     * @return the value of orderreturn.pid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.pid
     *
     * @param pid the value for orderreturn.pid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.price
     *
     * @return the value of orderreturn.price
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.price
     *
     * @param price the value for orderreturn.price
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.orderReturnTime
     *
     * @return the value of orderreturn.orderReturnTime
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Date getOrderreturntime() {
        return orderreturntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.orderReturnTime
     *
     * @param orderreturntime the value for orderreturn.orderReturnTime
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setOrderreturntime(Date orderreturntime) {
        this.orderreturntime = orderreturntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.orderReturnStatus
     *
     * @return the value of orderreturn.orderReturnStatus
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getOrderreturnstatus() {
        return orderreturnstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.orderReturnStatus
     *
     * @param orderreturnstatus the value for orderreturn.orderReturnStatus
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setOrderreturnstatus(Integer orderreturnstatus) {
        this.orderreturnstatus = orderreturnstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.isdelete
     *
     * @return the value of orderreturn.isdelete
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.isdelete
     *
     * @param isdelete the value for orderreturn.isdelete
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderreturn.orderReturnNote
     *
     * @return the value of orderreturn.orderReturnNote
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getOrderreturnnote() {
        return orderreturnnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderreturn.orderReturnNote
     *
     * @param orderreturnnote the value for orderreturn.orderReturnNote
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setOrderreturnnote(String orderreturnnote) {
        this.orderreturnnote = orderreturnnote;
    }
}