package com.woniu.entity;

public class Province {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column province.pname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String pname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pid
     *
     * @return the value of province.pid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pid
     *
     * @param pid the value for province.pid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column province.pname
     *
     * @return the value of province.pname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column province.pname
     *
     * @param pname the value for province.pname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setPname(String pname) {
        this.pname = pname;
    }
}