package com.woniu.entity;

public class ST {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.sid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_t.tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.sid
     *
     * @return the value of s_t.sid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.sid
     *
     * @param sid the value for s_t.sid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_t.tid
     *
     * @return the value of s_t.tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_t.tid
     *
     * @param tid the value for s_t.tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}