package com.woniu.entity;

public class Storeprodtype {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeprodtype.sptid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer sptid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeprodtype.sptname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String sptname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeprodtype.sid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeprodtype.parent_tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer parentTid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeprodtype.photo
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeprodtype.isdelete
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer isdelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column storeprodtype.note
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeprodtype.sptid
     *
     * @return the value of storeprodtype.sptid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getSptid() {
        return sptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeprodtype.sptid
     *
     * @param sptid the value for storeprodtype.sptid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setSptid(Integer sptid) {
        this.sptid = sptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeprodtype.sptname
     *
     * @return the value of storeprodtype.sptname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getSptname() {
        return sptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeprodtype.sptname
     *
     * @param sptname the value for storeprodtype.sptname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setSptname(String sptname) {
        this.sptname = sptname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeprodtype.sid
     *
     * @return the value of storeprodtype.sid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeprodtype.sid
     *
     * @param sid the value for storeprodtype.sid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeprodtype.parent_tid
     *
     * @return the value of storeprodtype.parent_tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getParentTid() {
        return parentTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeprodtype.parent_tid
     *
     * @param parentTid the value for storeprodtype.parent_tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setParentTid(Integer parentTid) {
        this.parentTid = parentTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeprodtype.photo
     *
     * @return the value of storeprodtype.photo
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeprodtype.photo
     *
     * @param photo the value for storeprodtype.photo
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeprodtype.isdelete
     *
     * @return the value of storeprodtype.isdelete
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeprodtype.isdelete
     *
     * @param isdelete the value for storeprodtype.isdelete
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column storeprodtype.note
     *
     * @return the value of storeprodtype.note
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column storeprodtype.note
     *
     * @param note the value for storeprodtype.note
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setNote(String note) {
        this.note = note;
    }
}