package com.woniu.entity;

public class Tree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.tname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.file
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tree.pid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    private String pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.tid
     *
     * @return the value of tree.tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.tid
     *
     * @param tid the value for tree.tid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.tname
     *
     * @return the value of tree.tname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.tname
     *
     * @param tname the value for tree.tname
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setTname(String tname) {
        this.tname = tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.file
     *
     * @return the value of tree.file
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.file
     *
     * @param file the value for tree.file
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setFile(String file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tree.pid
     *
     * @return the value of tree.pid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tree.pid
     *
     * @param pid the value for tree.pid
     *
     * @mbggenerated Tue Aug 20 16:07:27 CST 2019
     */
    public void setPid(String pid) {
        this.pid = pid;
    }
}