package com.woniu.entity;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uid
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uname
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.upass
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private String upass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.pay_count
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private String payCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.pay_pass
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private String payPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.user_realname
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private String userRealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.usex
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private Boolean usex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.uage
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private Integer uage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phone
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.province_id
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.province_name
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private String provinceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.city_id
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.city_name
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.zone_id
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private Integer zoneId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.zone_name
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private String zoneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.isdelete
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    private Integer isdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uid
     *
     * @return the value of userinfo.uid
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uid
     *
     * @param uid the value for userinfo.uid
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uname
     *
     * @return the value of userinfo.uname
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uname
     *
     * @param uname the value for userinfo.uname
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.upass
     *
     * @return the value of userinfo.upass
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public String getUpass() {
        return upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.upass
     *
     * @param upass the value for userinfo.upass
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setUpass(String upass) {
        this.upass = upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.pay_count
     *
     * @return the value of userinfo.pay_count
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public String getPayCount() {
        return payCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.pay_count
     *
     * @param payCount the value for userinfo.pay_count
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setPayCount(String payCount) {
        this.payCount = payCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.pay_pass
     *
     * @return the value of userinfo.pay_pass
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public String getPayPass() {
        return payPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.pay_pass
     *
     * @param payPass the value for userinfo.pay_pass
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setPayPass(String payPass) {
        this.payPass = payPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.user_realname
     *
     * @return the value of userinfo.user_realname
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public String getUserRealname() {
        return userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.user_realname
     *
     * @param userRealname the value for userinfo.user_realname
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setUserRealname(String userRealname) {
        this.userRealname = userRealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.usex
     *
     * @return the value of userinfo.usex
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public Boolean getUsex() {
        return usex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.usex
     *
     * @param usex the value for userinfo.usex
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setUsex(Boolean usex) {
        this.usex = usex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.uage
     *
     * @return the value of userinfo.uage
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public Integer getUage() {
        return uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.uage
     *
     * @param uage the value for userinfo.uage
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setUage(Integer uage) {
        this.uage = uage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phone
     *
     * @return the value of userinfo.phone
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phone
     *
     * @param phone the value for userinfo.phone
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.province_id
     *
     * @return the value of userinfo.province_id
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.province_id
     *
     * @param provinceId the value for userinfo.province_id
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.province_name
     *
     * @return the value of userinfo.province_name
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.province_name
     *
     * @param provinceName the value for userinfo.province_name
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.city_id
     *
     * @return the value of userinfo.city_id
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.city_id
     *
     * @param cityId the value for userinfo.city_id
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.city_name
     *
     * @return the value of userinfo.city_name
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.city_name
     *
     * @param cityName the value for userinfo.city_name
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.zone_id
     *
     * @return the value of userinfo.zone_id
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public Integer getZoneId() {
        return zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.zone_id
     *
     * @param zoneId the value for userinfo.zone_id
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setZoneId(Integer zoneId) {
        this.zoneId = zoneId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.zone_name
     *
     * @return the value of userinfo.zone_name
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public String getZoneName() {
        return zoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.zone_name
     *
     * @param zoneName the value for userinfo.zone_name
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.isdelete
     *
     * @return the value of userinfo.isdelete
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public Integer getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.isdelete
     *
     * @param isdelete the value for userinfo.isdelete
     *
     * @mbggenerated Wed Aug 21 16:09:25 CST 2019
     */
    public void setIsdelete(Integer isdelete) {
        this.isdelete = isdelete;
    }
}